# Generated by Django 5.0.6 on 2024-07-14 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('ack_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mobile_number', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accusedAccountNumbers', models.TextField(blank=True, null=True)),
                ('accusedSuspiciousItem', models.TextField(blank=True, null=True)),
                ('fraud_type', models.TextField()),
                ('steps_taken', models.TextField(blank=True, null=True)),
                ('files', models.URLField(blank=True, db_index=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in review', 'In Review'), ('visit ps', 'Visit Police Station'), ('in progress', 'In Progress'), ('closed', 'Closed')], default='Verification Pending', max_length=50)),
                ('investigating_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('fir_number', models.CharField(max_length=20)),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('place_of_occurrence', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_dispatch_from_ps', models.DateTimeField(blank=True, null=True)),
                ('name_of_complainant', models.CharField(max_length=255)),
                ('residence_of_complainant', models.TextField(blank=True, null=True)),
                ('name_of_accused', models.CharField(blank=True, max_length=255, null=True)),
                ('residence_of_accused', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('steps_taken_by_io', models.TextField(blank=True, null=True)),
                ('result_of_the_case', models.TextField()),
                ('complain', models.ManyToManyField(related_name='firs', to='ComplainApp.complains')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session_keys', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
