# Generated by Django 5.0.6 on 2024-07-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complains',
            old_name='investigating_officer',
            new_name='enquiry_officer',
        ),
    ]
