# Generated by Django 5.0.6 on 2024-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0002_rename_investigating_officer_complains_enquiry_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='amount_recovered',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='complains',
            name='fraudlent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
