# Generated by Django 5.0.6 on 2024-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0003_complains_amount_recovered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complains',
            old_name='accusedAccountNumbers',
            new_name='suspect_account_numbers',
        ),
        migrations.RemoveField(
            model_name='complains',
            name='accusedSuspiciousItem',
        ),
        migrations.AddField(
            model_name='complains',
            name='suspect_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='suspect_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='suspect_mobile_numbers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
