# Generated by Django 5.0.6 on 2024-06-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0004_adminactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('unconfirmed', 'Unconfirmed')], max_length=60)),
                ('details', models.TextField(blank=True, null=True)),
                ('complaints', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('unconfirmed', 'Unconfirmed')], max_length=60)),
                ('details', models.TextField(blank=True, null=True)),
                ('complaints', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('unconfirmed', 'Unconfirmed')], max_length=60)),
                ('details', models.TextField(blank=True, null=True)),
                ('complaints', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
