# Generated by Django 5.0.6 on 2024-07-16 13:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0004_rename_accusedaccountnumbers_complains_suspect_account_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='files',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='files'),
        ),
    ]
