# Generated by Django 5.0.6 on 2024-07-16 14:43

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0005_alter_complains_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='files',
        ),
        migrations.CreateModel(
            name='ComplainFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ComplainApp.complains')),
            ],
        ),
    ]
