# Generated by Django 5.0.6 on 2024-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0005_scamemail_scamlink_scamphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamlink',
            name='url',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
