# Generated by Django 5.0.6 on 2024-06-21 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0006_alter_scamlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
