# Generated by Django 5.0.6 on 2024-07-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0006_remove_complains_files_complainfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainfile',
            name='public_id',
        ),
    ]
