# Generated by Django 5.0.6 on 2024-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0007_complains_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in review', 'In Review'), ('visit ps', 'Visit Police Station'), ('in progress', 'In Progress'), ('closed', 'Closed (Reach out to Police Station)')], default='Pending', max_length=50),
        ),
    ]
