# Generated by Django 5.0.6 on 2024-07-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0007_remove_complainfile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='files',
            field=models.URLField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='ComplainFile',
        ),
    ]
