# Generated by Django 5.0.6 on 2024-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0008_complains_files_delete_complainfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
