# Generated by Django 5.0.6 on 2024-06-24 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0008_alter_complains_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='images_videos',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ComplainApp.complains')),
            ],
        ),
    ]
