# Generated by Django 5.0.6 on 2024-06-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0009_remove_complains_images_videos_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('complain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fir', serialize=False, to='ComplainApp.complains')),
                ('date', models.DateField()),
                ('fir_number', models.CharField(max_length=20)),
                ('place_of_occurrence', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_dispatch_from_ps', models.DateField(blank=True, null=True)),
                ('name_of_complainant', models.CharField(max_length=255)),
                ('residence_of_complainant', models.TextField(blank=True, null=True)),
                ('name_of_accused', models.CharField(blank=True, max_length=255, null=True)),
                ('residence_of_accused', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('section', models.TextField()),
                ('steps_taken_by_io', models.TextField()),
                ('result_of_the_case', models.TextField()),
            ],
        ),
    ]
