# Generated by Django 5.0.6 on 2024-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0009_alter_complains_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='place_of_incidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='upload_status',
            field=models.BooleanField(default=False),
        ),
    ]
