# Generated by Django 5.0.6 on 2024-07-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0010_complains_message_complains_place_of_incidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='place_of_incidence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
