# Generated by Django 5.0.6 on 2024-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0011_alter_fir_date_alter_fir_date_of_dispatch_from_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='steps_taken_by_io',
            field=models.TextField(blank=True, null=True),
        ),
    ]
