# Generated by Django 5.0.6 on 2024-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0012_alter_fir_description_alter_fir_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
