# Generated by Django 5.0.6 on 2024-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0013_complains_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='accusedAccountNumbers',
            field=models.TextField(blank=True, help_text='Enter Associated Account Numbers', null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='accusedSuspiciousItem',
            field=models.TextField(blank=True, help_text='Enter Items', null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='description',
            field=models.TextField(blank=True, help_text='Enter Fraud Description', null=True),
        ),
    ]
