# Generated by Django 5.0.6 on 2024-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0015_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='date_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
