# Generated by Django 5.0.6 on 2024-07-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0016_fir_date_reported_alter_fir_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='date',
            new_name='Date',
        ),
    ]
