# Generated by Django 5.0.6 on 2024-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainApp', '0017_rename_date_fir_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='complain',
        ),
        migrations.DeleteModel(
            name='ScamEmail',
        ),
        migrations.DeleteModel(
            name='ScamLink',
        ),
        migrations.DeleteModel(
            name='ScamPhone',
        ),
        migrations.AddField(
            model_name='complains',
            name='files',
            field=models.URLField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='accusedAccountNumbers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='accusedSuspiciousItem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='fraud_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complains',
            name='mobile_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complains',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in review', 'In Review'), ('visit ps', 'Visit Police Station'), ('in progress', 'In Progress'), ('closed', 'Closed (Reach out to Police Station)')], default='Verification Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
